[tool.poetry]
name = "cam2 Image Depth Maps"
version = "0.0.1"
description = ""
license = ""
authors = ["Nicholas M. Synovic <nicholas.synovic@gmail.com>"]
maintainers = ["Nicholas M. Synovic <nicholas.synovic@gmail.com>"]
readme = "README.md"
homepage = ""
documentation = ""
keywords = []
classifiers = []

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.13.9"
flake8 = "^4.0.1"
mypy = "^0.950"
bandit = "^1.7.4"
black = "^22.3.0"
isort = "^5.10.1"
autoflake = "^1.4"

[tool.poetry.scripts]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/NicholasSynovic/cam2_ImageDepthMaps/issues"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
