name: Release Project

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'

      - name: Install requirements
        run: python3 -m pip install poetry

      - name: Build Project
        run: poetry build -n

      - name: Release to GitHub
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          token: {{ secrets.TOKEN }}
